### PR TITLE
Switch "ATS" site to HERE branding, name to OTA Connect

### PR DESCRIPTION
**Pull request by tkfu**
This is currently pushed to http://docs-staging.atsgarage.com.s3-website.eu-central-1.amazonaws.com/, if you want to see it live.

### CODE REVIEW

**Review by merltron — COMMENTED** [review]
Found a hard-code instance of ATS Garage:

"Upload the root CA certificate to the server. To add a root CA certificate to ATS Garage, contact "

Implicit provisioning with a Hardware Security Module

**Comment by pattivacek** [comment]
> Found a hard-code instance of ATS Garage:

That's from the aktualizr repo. Want to make a PR for it, or do you need someone in embedded to do it?

**Review by merltron — COMMENTED** [review]
Change the email address in "troubleshooting"

"Contact support@atsgarage.com and we’ll do our best to help."

Change the email address in "understanding-the-ats-garage-client.html"

hello@atsgarage.com (footnote)

**Comment by tkfu** [comment]
Fixed all the comments from @merltron, opened up https://github.com/advancedtelematic/aktualizr/pull/933 for @patrickvacek's comment.

**Pull request merged**
