### PR TITLE
Add getting starting content to integrator guide

### PR DESCRIPTION
**Pull request by tkfu**
Opening a new PR for this, superseding #74. Needed a rebase, and correct branch names.

### CODE REVIEW

**Comment by eu-siemann** [comment]
Do we still want to keep the API Description part? I basically agree with Merlin that it doesn't belong to "Getting started". Maybe we can just provide a link there to the doxygen page.

**Comment by eu-siemann** [comment]
And thanks a lot for cleaning this up! I hope I will find some time soon to add the code examples.

**Comment by xaviergully** [comment]
@tkfu, @eu-smirnov , @merltron, could this PR be reviewed and finally approved ? Or is there some blocking points ?

**Comment by merltron** [comment]
> @tkfu, @eu-smirnov , @merltron, could this PR be reviewed and finally approved ? Or is there some blocking points ?

@xaviergully  The blocking point is primarily time and resource. However, we also lack the correct place in the doc structure which is a wider topic that we are working on. Maybe we could incorporate this ticket into a sprint?

**Pull request merged**
